#!/bin/bash
set -e

# Generate API documentation from XML comments using xmldoc2md

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"
DOCS_API_DIR="$ROOT_DIR/docs/docs/api"

echo "=== Generating API Documentation ==="

# Ensure dotnet tools are restored
echo "Restoring dotnet tools..."
cd "$ROOT_DIR"
dotnet tool restore

# Build the project with XML documentation
echo "Building project with XML documentation..."
dotnet build -c Release

# Find the XML documentation file (prefer bin over obj)
XML_FILE=$(find "$ROOT_DIR/src" -name "Bogoware.Monads.xml" -path "*/bin/Release/*" | head -1)

if [ -z "$XML_FILE" ]; then
    echo "Error: Could not find Bogoware.Monads.xml"
    echo "Make sure the project generates XML documentation on build."
    exit 1
fi

echo "Found XML documentation: $XML_FILE"

# Find the DLL file (prefer bin over obj, exclude ref assemblies)
DLL_FILE=$(find "$ROOT_DIR/src" -name "Bogoware.Monads.dll" -path "*/bin/Release/*" | grep -v "/ref/" | head -1)

if [ -z "$DLL_FILE" ]; then
    echo "Error: Could not find Bogoware.Monads.dll"
    exit 1
fi

echo "Found DLL: $DLL_FILE"

# Create output directory
mkdir -p "$DOCS_API_DIR"

# Generate markdown documentation
echo "Generating markdown from XML documentation..."
dotnet xmldoc2md "$DLL_FILE" -o "$DOCS_API_DIR" --index-page-name index --github-pages

# Add frontmatter to generated files
echo "Adding frontmatter to generated files..."
add_frontmatter() {
    local file="$1"
    local title="$2"
    local position="${3:-99}"

    if [ -f "$file" ]; then
        local temp_file=$(mktemp)
        echo "---" > "$temp_file"
        echo "title: \"$title\"" >> "$temp_file"
        echo "sidebar_position: $position" >> "$temp_file"
        echo "---" >> "$temp_file"
        echo "" >> "$temp_file"
        cat "$file" >> "$temp_file"
        mv "$temp_file" "$file"
    fi
}

# Process generated files (excluding index.md which was regenerated)
for file in "$DOCS_API_DIR"/*.md; do
    if [ -f "$file" ]; then
        filename=$(basename "$file" .md)
        # Skip the index file as it's autogenerated
        if [ "$filename" = "index" ]; then
            # Add frontmatter to index
            add_frontmatter "$file" "API Reference" 1
        else
            # Extract title from filename (remove namespace prefix if present)
            title="${filename#bogoware.monads.}"
            add_frontmatter "$file" "$title"
        fi
        echo "Processed: $filename"
    fi
done

echo "=== API Documentation Generated ==="
echo "Output directory: $DOCS_API_DIR"
