import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    'intro',
    'changelog',
    {
      type: 'category',
      label: 'Getting Started',
      items: [{type: 'autogenerated', dirName: 'getting-started'}],
      collapsed: false,
    },
    {
      type: 'category',
      label: 'Concepts',
      items: [{type: 'autogenerated', dirName: 'concepts'}],
    },
    {
      type: 'category',
      label: 'Guides',
      items: [{type: 'autogenerated', dirName: 'guides'}],
    },
  ],
  apiSidebar: [
    {
      type: 'autogenerated',
      dirName: 'api',
    },
  ],
};

export default sidebars;
